# Generated by Django 3.0.7 on 2020-06-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('main_category', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('K', 'Kids')], max_length=1)),
                ('sub_category', models.CharField(choices=[('RUNNING', 'Running'), ('FOOTBALL', 'Football'), ('SNEAKERS', 'Sneakers'), ('FORMAL', 'Formal')], max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('imageURL', models.URLField()),
            ],
        ),
    ]
