# Generated by Django 3.0.7 on 2020-06-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('M', 'Men'), ('F', 'Women'), ('K', 'Kids')], max_length=1),
        ),
    ]
