# Generated by Django 3.0.7 on 2020-06-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_in_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('NIKE', 'Nike'), ('ADIDAS', 'Adidas')], default='NIKE', max_length=20),
        ),
    ]
