# Generated by Django 3.0.7 on 2020-06-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200630_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('FOOTBALL', 'Football'), ('CASUAL', 'Casual'), ('FORMAL', 'Formal')], max_length=10),
        ),
    ]
