# Generated by Django 3.0.7 on 2020-06-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200630_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='main_category',
            new_name='gender',
        ),
    ]
