# Generated by Django 3.0.7 on 2020-07-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_items_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('NIKE', 'Nike'), ('ADIDAS', 'Adidas'), ('HUSHPUPPIES', 'Hush Puppies'), ('Reebok', 'Reebok'), ('Vans', 'Vans'), ('Puma', 'Puma')], default='NIKE', max_length=20),
        ),
    ]
